#!/bin/sh
goRun(){
  go run . -ro ../golang ${GOROOT}/src/$*
}

go run . -g=wasm -ro ../golang "${GOROOT}/src/syscall" &&\
GOOS=windows go run . -c=windows -ro ../golang "${GOROOT}/src/syscall" &&\
go run . -c=linux -e=GOOS=linux -ro ../golang "${GOROOT}/src/syscall" &&\
go run . -c=darwin -e=GOOS=darwin -ro ../golang "${GOROOT}/src/syscall"

goRun archive/tar
goRun archive/zip
goRun bufio
#goRun builtin
goRun bytes
#goRun cmp
goRun compress/bzip2
goRun compress/flate
goRun compress/gzip
goRun compress/lzw
goRun compress/zlib
goRun container/heap
goRun container/list
goRun container/ring
goRun context
goRun crypto
goRun crypto/aes
#goRun crypto/boring
goRun crypto/cipher
goRun crypto/des
goRun crypto/dsa
goRun crypto/ecdh
goRun crypto/ecdsa
goRun crypto/ed25519
goRun crypto/elliptic
goRun crypto/hmac
goRun crypto/md5
goRun crypto/rand
goRun crypto/rc4
goRun crypto/rsa
goRun crypto/sha1
goRun crypto/sha256
goRun crypto/sha512
goRun crypto/subtle
goRun crypto/tls
#goRun crypto/tls/fipsonly
goRun crypto/x509
goRun crypto/x509/pkix
goRun encoding
goRun encoding/ascii85
goRun encoding/asn1
goRun encoding/base32
goRun encoding/base64
goRun encoding/binary
goRun encoding/csv
goRun encoding/gob
goRun encoding/hex
goRun encoding/json
goRun encoding/pem
goRun encoding/xml
goRun errors
#goRun expvar
#goRun flag
goRun fmt
goRun hash
goRun hash/adler32
goRun hash/crc32
goRun hash/crc64
goRun hash/fnv
goRun hash/maphash
goRun html
goRun html/template
goRun image
goRun image/color
goRun image/color/palette
goRun image/draw
goRun image/gif
goRun image/jpeg
goRun image/png
goRun index/suffixarray
goRun io
goRun io/fs
#goRun io/ioutil
goRun log
goRun log/slog
#goRun log/syslog
#goRun maps
goRun math
goRun math/big
goRun math/bits
goRun math/cmplx
goRun math/rand
goRun mime
goRun mime/multipart
goRun mime/quotedprintable
goRun net
goRun net/http
goRun net/http/cgi
goRun net/http/cookiejar
goRun net/http/fcgi
goRun net/http/httptest
goRun net/http/httptrace
goRun net/http/httputil
goRun net/http/pprof
goRun net/mail
goRun net/netip
goRun net/rpc
goRun net/rpc/jsonrpc
goRun net/smtp
goRun net/textproto
goRun net/url
goRun os
goRun os/exec
goRun os/signal
goRun os/user
goRun path
goRun path/filepath
goRun reflect
goRun regexp
goRun regexp/syntax
#goRun slices
goRun sort
goRun strconv
goRun strings
goRun sync
goRun sync/atomic
#goRun syscall
goRun text/scanner
goRun text/tabwriter
goRun text/template
goRun text/template/parse
goRun time
goRun unicode
goRun unicode/utf16
goRun unicode/utf8
#goRun unsafe
