// Code generated by define_gene; DO NOT EDIT.
package pem

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/pem"
	_ "github.com/ZenLiuCN/engine/golang/io"
)

var (
	//go:embed encoding_pem.d.ts
	EncodingPemDefine   []byte
	EncodingPemDeclared = map[string]any{
		"encode":         pem.Encode,
		"encodeToMemory": pem.EncodeToMemory,
		"decode":         pem.Decode,

		"emptyBlock": func() (v pem.Block) {
			return v
		},
		"refBlock": func() *pem.Block {
			var x pem.Block
			return &x
		},
		"refOfBlock": func(x pem.Block) *pem.Block {
			return &x
		}}
)

func init() {
	engine.RegisterModule(EncodingPemModule{})
}

type EncodingPemModule struct{}

func (S EncodingPemModule) Identity() string {
	return "golang/encoding/pem"
}
func (S EncodingPemModule) TypeDefine() []byte {
	return EncodingPemDefine
}
func (S EncodingPemModule) Exports() map[string]any {
	return EncodingPemDeclared
}
