// Code generated by define_gene; DO NOT EDIT.
package csv

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/csv"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
)

var (
	//go:embed encoding_csv.d.ts
	EncodingCsvDefine   []byte
	EncodingCsvDeclared = map[string]any{
		"newWriter":        csv.NewWriter,
		"ErrBareQuote":     csv.ErrBareQuote,
		"ErrFieldCount":    csv.ErrFieldCount,
		"ErrQuote":         csv.ErrQuote,
		"ErrTrailingComma": csv.ErrTrailingComma,
		"newReader":        csv.NewReader,
	}
)

func init() {
	engine.RegisterModule(EncodingCsvModule{})
}

type EncodingCsvModule struct{}

func (S EncodingCsvModule) Identity() string {
	return "golang/encoding/csv"
}
func (S EncodingCsvModule) TypeDefine() []byte {
	return EncodingCsvDefine
}
func (S EncodingCsvModule) Exports() map[string]any {
	return EncodingCsvDeclared
}
