// Code generated by define_gene; DO NOT EDIT.
package vc

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/service/vc/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/vc"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_vc.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceVcDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceVcDeclared = map[string]any{
		"newService": vc.NewService,
	}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceVcModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceVcModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceVcModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/vc"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceVcModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceVcDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceVcModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceVcDeclared
}
