// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection
// Code generated by define_gene; DO NOT EDIT.
declare module 'golang/crypto/aes'{
	// @ts-ignore
	import * as cipher from 'golang/crypto/cipher'
	// @ts-ignore
	import type {int,GoError,error} from 'go'
	//16
	export const BlockSize:int
	export interface KeySizeError extends int,GoError{
		error():string
	}
	export function newCipher(key:Uint8Array):cipher.Block
}
