// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection
// Code generated by define_gene; DO NOT EDIT.
declare module 'golang/image/color/palette'{

	// @ts-ignore
	import * as color from 'golang/image/color'
	// @ts-ignore
	import type {Ref} from 'go'
	export const Plan9:color.Color[]
	export const WebSafe:color.Color[]
}