// Code generated by define_gene; DO NOT EDIT.
package larktenant

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/context"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/tenant/v2"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_tenant_v2.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceTenant2Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceTenant2Declared = map[string]any{
		"newDepartmentIdBuilder":     larktenant.NewDepartmentIdBuilder,
		"newProductI18nNameBuilder":  larktenant.NewProductI18nNameBuilder,
		"newTenantAssignInfoBuilder": larktenant.NewTenantAssignInfoBuilder,
		"newTenantBuilder":           larktenant.NewTenantBuilder,
		"New":                        larktenant.New,
		"newAvatarBuilder":           larktenant.NewAvatarBuilder,

		"emptyAvatar":                                  engine.Empty[larktenant.Avatar],
		"emptyRefAvatar":                               engine.EmptyRefer[larktenant.Avatar],
		"refOfAvatar":                                  engine.ReferOf[larktenant.Avatar],
		"unRefAvatar":                                  engine.UnRefer[larktenant.Avatar],
		"emptyProductI18nNameBuilder":                  engine.Empty[larktenant.ProductI18nNameBuilder],
		"emptyRefProductI18nNameBuilder":               engine.EmptyRefer[larktenant.ProductI18nNameBuilder],
		"refOfProductI18nNameBuilder":                  engine.ReferOf[larktenant.ProductI18nNameBuilder],
		"unRefProductI18nNameBuilder":                  engine.UnRefer[larktenant.ProductI18nNameBuilder],
		"emptyTenant":                                  engine.Empty[larktenant.Tenant],
		"emptyRefTenant":                               engine.EmptyRefer[larktenant.Tenant],
		"refOfTenant":                                  engine.ReferOf[larktenant.Tenant],
		"unRefTenant":                                  engine.UnRefer[larktenant.Tenant],
		"emptyTenantAssignInfo":                        engine.Empty[larktenant.TenantAssignInfo],
		"emptyRefTenantAssignInfo":                     engine.EmptyRefer[larktenant.TenantAssignInfo],
		"refOfTenantAssignInfo":                        engine.ReferOf[larktenant.TenantAssignInfo],
		"unRefTenantAssignInfo":                        engine.UnRefer[larktenant.TenantAssignInfo],
		"emptyQueryTenantProductAssignInfoRespData":    engine.Empty[larktenant.QueryTenantProductAssignInfoRespData],
		"emptyRefQueryTenantProductAssignInfoRespData": engine.EmptyRefer[larktenant.QueryTenantProductAssignInfoRespData],
		"refOfQueryTenantProductAssignInfoRespData":    engine.ReferOf[larktenant.QueryTenantProductAssignInfoRespData],
		"unRefQueryTenantProductAssignInfoRespData":    engine.UnRefer[larktenant.QueryTenantProductAssignInfoRespData],
		"emptyTenantBuilder":                           engine.Empty[larktenant.TenantBuilder],
		"emptyRefTenantBuilder":                        engine.EmptyRefer[larktenant.TenantBuilder],
		"refOfTenantBuilder":                           engine.ReferOf[larktenant.TenantBuilder],
		"unRefTenantBuilder":                           engine.UnRefer[larktenant.TenantBuilder],
		"emptyAvatarBuilder":                           engine.Empty[larktenant.AvatarBuilder],
		"emptyRefAvatarBuilder":                        engine.EmptyRefer[larktenant.AvatarBuilder],
		"refOfAvatarBuilder":                           engine.ReferOf[larktenant.AvatarBuilder],
		"unRefAvatarBuilder":                           engine.UnRefer[larktenant.AvatarBuilder],
		"emptyProductI18nName":                         engine.Empty[larktenant.ProductI18nName],
		"emptyRefProductI18nName":                      engine.EmptyRefer[larktenant.ProductI18nName],
		"refOfProductI18nName":                         engine.ReferOf[larktenant.ProductI18nName],
		"unRefProductI18nName":                         engine.UnRefer[larktenant.ProductI18nName],
		"emptyQueryTenantRespData":                     engine.Empty[larktenant.QueryTenantRespData],
		"emptyRefQueryTenantRespData":                  engine.EmptyRefer[larktenant.QueryTenantRespData],
		"refOfQueryTenantRespData":                     engine.ReferOf[larktenant.QueryTenantRespData],
		"unRefQueryTenantRespData":                     engine.UnRefer[larktenant.QueryTenantRespData],
		"emptyTenantAssignInfoBuilder":                 engine.Empty[larktenant.TenantAssignInfoBuilder],
		"emptyRefTenantAssignInfoBuilder":              engine.EmptyRefer[larktenant.TenantAssignInfoBuilder],
		"refOfTenantAssignInfoBuilder":                 engine.ReferOf[larktenant.TenantAssignInfoBuilder],
		"unRefTenantAssignInfoBuilder":                 engine.UnRefer[larktenant.TenantAssignInfoBuilder],
		"emptyDepartmentId":                            engine.Empty[larktenant.DepartmentId],
		"emptyRefDepartmentId":                         engine.EmptyRefer[larktenant.DepartmentId],
		"refOfDepartmentId":                            engine.ReferOf[larktenant.DepartmentId],
		"unRefDepartmentId":                            engine.UnRefer[larktenant.DepartmentId],
		"emptyDepartmentIdBuilder":                     engine.Empty[larktenant.DepartmentIdBuilder],
		"emptyRefDepartmentIdBuilder":                  engine.EmptyRefer[larktenant.DepartmentIdBuilder],
		"refOfDepartmentIdBuilder":                     engine.ReferOf[larktenant.DepartmentIdBuilder],
		"unRefDepartmentIdBuilder":                     engine.UnRefer[larktenant.DepartmentIdBuilder],
		"emptyQueryTenantProductAssignInfoResp":        engine.Empty[larktenant.QueryTenantProductAssignInfoResp],
		"emptyRefQueryTenantProductAssignInfoResp":     engine.EmptyRefer[larktenant.QueryTenantProductAssignInfoResp],
		"refOfQueryTenantProductAssignInfoResp":        engine.ReferOf[larktenant.QueryTenantProductAssignInfoResp],
		"unRefQueryTenantProductAssignInfoResp":        engine.UnRefer[larktenant.QueryTenantProductAssignInfoResp],
		"emptyQueryTenantResp":                         engine.Empty[larktenant.QueryTenantResp],
		"emptyRefQueryTenantResp":                      engine.EmptyRefer[larktenant.QueryTenantResp],
		"refOfQueryTenantResp":                         engine.ReferOf[larktenant.QueryTenantResp],
		"unRefQueryTenantResp":                         engine.UnRefer[larktenant.QueryTenantResp],
		"emptyV2":                                      engine.Empty[larktenant.V2],
		"emptyRefV2":                                   engine.EmptyRefer[larktenant.V2],
		"refOfV2":                                      engine.ReferOf[larktenant.V2],
		"unRefV2":                                      engine.UnRefer[larktenant.V2]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceTenant2Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceTenant2Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceTenant2Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/tenant/v2"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceTenant2Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceTenant2Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceTenant2Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceTenant2Declared
}
