// Code generated by define_gene; DO NOT EDIT.
package zlib

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"compress/zlib"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
)

var (
	//go:embed compress_zlib.d.ts
	CompressZlibDefine   []byte
	CompressZlibDeclared = map[string]any{
		"BestSpeed":          zlib.BestSpeed,
		"newWriter":          zlib.NewWriter,
		"newWriterLevelDict": zlib.NewWriterLevelDict,
		"ErrChecksum":        zlib.ErrChecksum,
		"newReaderDict":      zlib.NewReaderDict,
		"newWriterLevel":     zlib.NewWriterLevel,
		"BestCompression":    zlib.BestCompression,
		"DefaultCompression": zlib.DefaultCompression,
		"ErrHeader":          zlib.ErrHeader,
		"ErrDictionary":      zlib.ErrDictionary,
		"HuffmanOnly":        zlib.HuffmanOnly,
		"newReader":          zlib.NewReader,
		"NoCompression":      zlib.NoCompression,
	}
)

func init() {
	engine.RegisterModule(CompressZlibModule{})
}

type CompressZlibModule struct{}

func (S CompressZlibModule) Identity() string {
	return "golang/compress/zlib"
}
func (S CompressZlibModule) TypeDefine() []byte {
	return CompressZlibDefine
}
func (S CompressZlibModule) Exports() map[string]any {
	return CompressZlibDeclared
}
