// Code generated by "stringer -type=AstNode"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AstNothing-0]
	_ = x[AstMethodDecl-1]
	_ = x[AstMethodStarDecl-2]
	_ = x[AstMethodIdentDecl-3]
	_ = x[AstFuncDecl-4]
	_ = x[AstIdent-5]
	_ = x[AstSelectorExpr-6]
	_ = x[AstStarExpr-7]
	_ = x[AstFuncType-8]
	_ = x[AstArrayType-9]
	_ = x[AstMapType-10]
	_ = x[AstStructType-11]
	_ = x[AstInterfaceType-12]
	_ = x[AstChanType-13]
	_ = x[AstEllipsis-14]
	_ = x[AstNodeBuiltInMax-15]
}

const _AstNode_name = "AstNothingAstMethodDeclAstMethodStarDeclAstMethodIdentDeclAstFuncDeclAstIdentAstSelectorExprAstStarExprAstFuncTypeAstArrayTypeAstMapTypeAstStructTypeAstInterfaceTypeAstChanTypeAstEllipsisAstNodeBuiltInMax"

var _AstNode_index = [...]uint8{0, 10, 23, 40, 58, 69, 77, 92, 103, 114, 126, 136, 149, 165, 176, 187, 204}

func (i AstNode) String() string {
	if i < 0 || i >= AstNode(len(_AstNode_index)-1) {
		return "AstNode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AstNode_name[_AstNode_index[i]:_AstNode_index[i+1]]
}
