// Code generated by define_gene; DO NOT EDIT.
package larkdrive

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	"github.com/larksuite/oapi-sdk-go/v3/service/drive/v2"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_drive_v2.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceDrive2Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceDrive2Declared = map[string]any{
		"LinkShareEntityTenantReadable":                  larkdrive.LinkShareEntityTenantReadable,
		"TokenTypePatchPermissionPublicSlides":           larkdrive.TokenTypePatchPermissionPublicSlides,
		"CommentEntityAnyoneCanEdit":                     larkdrive.CommentEntityAnyoneCanEdit,
		"ManageCollaboratorEntityCollaboratorCanEdit":    larkdrive.ManageCollaboratorEntityCollaboratorCanEdit,
		"ShareEntitySameTenant":                          larkdrive.ShareEntitySameTenant,
		"TokenTypeSheet":                                 larkdrive.TokenTypeSheet,
		"ExternalAccessEntityClosed":                     larkdrive.ExternalAccessEntityClosed,
		"newMyLikeBuilder":                               larkdrive.NewMyLikeBuilder,
		"SecurityEntityAnyoneCanView":                    larkdrive.SecurityEntityAnyoneCanView,
		"TokenTypeBitable":                               larkdrive.TokenTypeBitable,
		"ExternalAccessEntityOpen":                       larkdrive.ExternalAccessEntityOpen,
		"LinkShareEntityPartnerTenantEditable":           larkdrive.LinkShareEntityPartnerTenantEditable,
		"New":                                            larkdrive.New,
		"newImportJobBuilder":                            larkdrive.NewImportJobBuilder,
		"newSecureLabelBuilder":                          larkdrive.NewSecureLabelBuilder,
		"ExternalAccessEntityAllowSharePartnerTenant":    larkdrive.ExternalAccessEntityAllowSharePartnerTenant,
		"LinkShareEntityAnyoneReadable":                  larkdrive.LinkShareEntityAnyoneReadable,
		"LinkShareEntityTenantEditable":                  larkdrive.LinkShareEntityTenantEditable,
		"ManageCollaboratorEntityCollaboratorFullAccess": larkdrive.ManageCollaboratorEntityCollaboratorFullAccess,
		"newExportJobBuilder":                            larkdrive.NewExportJobBuilder,
		"newPatchPermissionPublicReqBuilder":             larkdrive.NewPatchPermissionPublicReqBuilder,
		"TokenTypePatchPermissionPublicDocx":             larkdrive.TokenTypePatchPermissionPublicDocx,
		"TokenTypeMindnote":                              larkdrive.TokenTypeMindnote,
		"TokenTypeSlides":                                larkdrive.TokenTypeSlides,
		"LinkShareEntityPartnerTenantReadable":           larkdrive.LinkShareEntityPartnerTenantReadable,
		"CopyEntityOnlyFullAccess":                       larkdrive.CopyEntityOnlyFullAccess,
		"LinkShareEntityClosed":                          larkdrive.LinkShareEntityClosed,
		"newGetPermissionPublicReqBuilder":               larkdrive.NewGetPermissionPublicReqBuilder,
		"TokenTypePatchPermissionPublicSheet":            larkdrive.TokenTypePatchPermissionPublicSheet,
		"CommentEntityAnyoneCanView":                     larkdrive.CommentEntityAnyoneCanView,
		"CopyEntityAnyoneCanEdit":                        larkdrive.CopyEntityAnyoneCanEdit,
		"LinkShareEntityAnyoneEditable":                  larkdrive.LinkShareEntityAnyoneEditable,
		"newDepartmentIdBuilder":                         larkdrive.NewDepartmentIdBuilder,
		"newImportJobMountPointBuilder":                  larkdrive.NewImportJobMountPointBuilder,
		"TokenTypeDoc":                                   larkdrive.TokenTypeDoc,
		"TokenTypeMinutes":                               larkdrive.TokenTypeMinutes,
		"newFileLikeBuilder":                             larkdrive.NewFileLikeBuilder,
		"TokenTypeWiki":                                  larkdrive.TokenTypeWiki,
		"ManageCollaboratorEntityCollaboratorCanView":    larkdrive.ManageCollaboratorEntityCollaboratorCanView,
		"newPermissionPublicBuilder":                     larkdrive.NewPermissionPublicBuilder,
		"SecurityEntityAnyoneCanEdit":                    larkdrive.SecurityEntityAnyoneCanEdit,
		"TokenTypePatchPermissionPublicWiki":             larkdrive.TokenTypePatchPermissionPublicWiki,
		"ShareEntityAnyone":                              larkdrive.ShareEntityAnyone,
		"TokenTypeFile":                                  larkdrive.TokenTypeFile,
		"TokenTypePatchPermissionPublicMindnote":         larkdrive.TokenTypePatchPermissionPublicMindnote,
		"TokenTypePatchPermissionPublicMinutes":          larkdrive.TokenTypePatchPermissionPublicMinutes,
		"CopyEntityAnyoneCanView":                        larkdrive.CopyEntityAnyoneCanView,
		"SecurityEntityOnlyFullAccess":                   larkdrive.SecurityEntityOnlyFullAccess,
		"TokenTypeDocx":                                  larkdrive.TokenTypeDocx,
		"TokenTypePatchPermissionPublicBitable":          larkdrive.TokenTypePatchPermissionPublicBitable,
		"TokenTypePatchPermissionPublicDoc":              larkdrive.TokenTypePatchPermissionPublicDoc,
		"TokenTypePatchPermissionPublicFile":             larkdrive.TokenTypePatchPermissionPublicFile,

		"emptyPatchPermissionPublicReq":         engine.Empty[larkdrive.PatchPermissionPublicReq],
		"emptyRefPatchPermissionPublicReq":      engine.EmptyRefer[larkdrive.PatchPermissionPublicReq],
		"refOfPatchPermissionPublicReq":         engine.ReferOf[larkdrive.PatchPermissionPublicReq],
		"unRefPatchPermissionPublicReq":         engine.UnRefer[larkdrive.PatchPermissionPublicReq],
		"emptyExportJob":                        engine.Empty[larkdrive.ExportJob],
		"emptyRefExportJob":                     engine.EmptyRefer[larkdrive.ExportJob],
		"refOfExportJob":                        engine.ReferOf[larkdrive.ExportJob],
		"unRefExportJob":                        engine.UnRefer[larkdrive.ExportJob],
		"emptyGetPermissionPublicRespData":      engine.Empty[larkdrive.GetPermissionPublicRespData],
		"emptyRefGetPermissionPublicRespData":   engine.EmptyRefer[larkdrive.GetPermissionPublicRespData],
		"refOfGetPermissionPublicRespData":      engine.ReferOf[larkdrive.GetPermissionPublicRespData],
		"unRefGetPermissionPublicRespData":      engine.UnRefer[larkdrive.GetPermissionPublicRespData],
		"emptyV2":                               engine.Empty[larkdrive.V2],
		"emptyRefV2":                            engine.EmptyRefer[larkdrive.V2],
		"refOfV2":                               engine.ReferOf[larkdrive.V2],
		"unRefV2":                               engine.UnRefer[larkdrive.V2],
		"emptyFileLike":                         engine.Empty[larkdrive.FileLike],
		"emptyRefFileLike":                      engine.EmptyRefer[larkdrive.FileLike],
		"refOfFileLike":                         engine.ReferOf[larkdrive.FileLike],
		"unRefFileLike":                         engine.UnRefer[larkdrive.FileLike],
		"emptyImportJobMountPoint":              engine.Empty[larkdrive.ImportJobMountPoint],
		"emptyRefImportJobMountPoint":           engine.EmptyRefer[larkdrive.ImportJobMountPoint],
		"refOfImportJobMountPoint":              engine.ReferOf[larkdrive.ImportJobMountPoint],
		"unRefImportJobMountPoint":              engine.UnRefer[larkdrive.ImportJobMountPoint],
		"emptySecureLabel":                      engine.Empty[larkdrive.SecureLabel],
		"emptyRefSecureLabel":                   engine.EmptyRefer[larkdrive.SecureLabel],
		"refOfSecureLabel":                      engine.ReferOf[larkdrive.SecureLabel],
		"unRefSecureLabel":                      engine.UnRefer[larkdrive.SecureLabel],
		"emptyGetPermissionPublicReq":           engine.Empty[larkdrive.GetPermissionPublicReq],
		"emptyRefGetPermissionPublicReq":        engine.EmptyRefer[larkdrive.GetPermissionPublicReq],
		"refOfGetPermissionPublicReq":           engine.ReferOf[larkdrive.GetPermissionPublicReq],
		"unRefGetPermissionPublicReq":           engine.UnRefer[larkdrive.GetPermissionPublicReq],
		"emptyGetPermissionPublicResp":          engine.Empty[larkdrive.GetPermissionPublicResp],
		"emptyRefGetPermissionPublicResp":       engine.EmptyRefer[larkdrive.GetPermissionPublicResp],
		"refOfGetPermissionPublicResp":          engine.ReferOf[larkdrive.GetPermissionPublicResp],
		"unRefGetPermissionPublicResp":          engine.UnRefer[larkdrive.GetPermissionPublicResp],
		"emptyPatchPermissionPublicResp":        engine.Empty[larkdrive.PatchPermissionPublicResp],
		"emptyRefPatchPermissionPublicResp":     engine.EmptyRefer[larkdrive.PatchPermissionPublicResp],
		"refOfPatchPermissionPublicResp":        engine.ReferOf[larkdrive.PatchPermissionPublicResp],
		"unRefPatchPermissionPublicResp":        engine.UnRefer[larkdrive.PatchPermissionPublicResp],
		"emptyPatchPermissionPublicRespData":    engine.Empty[larkdrive.PatchPermissionPublicRespData],
		"emptyRefPatchPermissionPublicRespData": engine.EmptyRefer[larkdrive.PatchPermissionPublicRespData],
		"refOfPatchPermissionPublicRespData":    engine.ReferOf[larkdrive.PatchPermissionPublicRespData],
		"unRefPatchPermissionPublicRespData":    engine.UnRefer[larkdrive.PatchPermissionPublicRespData],
		"emptyImportJob":                        engine.Empty[larkdrive.ImportJob],
		"emptyRefImportJob":                     engine.EmptyRefer[larkdrive.ImportJob],
		"refOfImportJob":                        engine.ReferOf[larkdrive.ImportJob],
		"unRefImportJob":                        engine.UnRefer[larkdrive.ImportJob],
		"emptyMyLike":                           engine.Empty[larkdrive.MyLike],
		"emptyRefMyLike":                        engine.EmptyRefer[larkdrive.MyLike],
		"refOfMyLike":                           engine.ReferOf[larkdrive.MyLike],
		"unRefMyLike":                           engine.UnRefer[larkdrive.MyLike],
		"emptyPermissionPublic":                 engine.Empty[larkdrive.PermissionPublic],
		"emptyRefPermissionPublic":              engine.EmptyRefer[larkdrive.PermissionPublic],
		"refOfPermissionPublic":                 engine.ReferOf[larkdrive.PermissionPublic],
		"unRefPermissionPublic":                 engine.UnRefer[larkdrive.PermissionPublic],
		"emptyDepartmentId":                     engine.Empty[larkdrive.DepartmentId],
		"emptyRefDepartmentId":                  engine.EmptyRefer[larkdrive.DepartmentId],
		"refOfDepartmentId":                     engine.ReferOf[larkdrive.DepartmentId],
		"unRefDepartmentId":                     engine.UnRefer[larkdrive.DepartmentId]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceDrive2Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceDrive2Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceDrive2Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/drive/v2"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceDrive2Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceDrive2Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceDrive2Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceDrive2Declared
}
