// Code generated by define_gene; DO NOT EDIT.
package hash

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/io"
	"hash"
)

var (
	//go:embed hash.d.ts
	HashDefine   []byte
	HashDeclared = map[string]any{}
)

func init() {
	engine.RegisterModule(HashModule{})
}

type HashModule struct{}

func (S HashModule) Identity() string {
	return "golang/hash"
}
func (S HashModule) TypeDefine() []byte {
	return HashDefine
}
func (S HashModule) Exports() map[string]any {
	return HashDeclared
}
