// Code generated by define_gene; DO NOT EDIT.
package mdm

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/service/mdm/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/mdm"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_mdm.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceMdmDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceMdmDeclared = map[string]any{
		"newService": mdm.NewService,

		"emptyService":    engine.Empty[mdm.Service],
		"emptyRefService": engine.EmptyRefer[mdm.Service],
		"refOfService":    engine.ReferOf[mdm.Service],
		"unRefService":    engine.UnRefer[mdm.Service]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceMdmModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceMdmModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceMdmModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/mdm"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceMdmModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceMdmDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceMdmModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceMdmDeclared
}
