// Code generated by define_gene; DO NOT EDIT.
package json

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/json"
	_ "github.com/ZenLiuCN/engine/modules/golang/bytes"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
	_ "github.com/ZenLiuCN/engine/modules/golang/reflect"
)

var (
	//go:embed encoding_json.d.ts
	EncodingJsonDefine   []byte
	EncodingJsonDeclared = map[string]any{
		"compact":       json.Compact,
		"htmlEscape":    json.HTMLEscape,
		"indent":        json.Indent,
		"marshalIndent": json.MarshalIndent,
		"marshal":       json.Marshal,
		"newDecoder":    json.NewDecoder,
		"newEncoder":    json.NewEncoder,
		"unmarshal":     json.Unmarshal,
		"valid":         json.Valid,
	}
)

func init() {
	engine.RegisterModule(EncodingJsonModule{})
}

type EncodingJsonModule struct{}

func (S EncodingJsonModule) Identity() string {
	return "golang/encoding/json"
}
func (S EncodingJsonModule) TypeDefine() []byte {
	return EncodingJsonDefine
}
func (S EncodingJsonModule) Exports() map[string]any {
	return EncodingJsonDeclared
}
