// Code generated by define_gene; DO NOT EDIT.
package exec

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/context"
	_ "github.com/ZenLiuCN/engine/golang/io"
	_ "github.com/ZenLiuCN/engine/golang/os"
	_ "github.com/ZenLiuCN/engine/golang/syscall"
	_ "github.com/ZenLiuCN/engine/golang/time"
	"os/exec"
)

var (
	//go:embed os_exec.d.ts
	OsExecDefine   []byte
	OsExecDeclared = map[string]any{
		"lookPath":       exec.LookPath,
		"command":        exec.Command,
		"commandContext": exec.CommandContext,
		"ErrDot":         exec.ErrDot,
		"ErrNotFound":    exec.ErrNotFound,
		"ErrWaitDelay":   exec.ErrWaitDelay,

		"emptyCmd": func() (v exec.Cmd) {
			return v
		},
		"refCmd": func() *exec.Cmd {
			var x exec.Cmd
			return &x
		},
		"refOfCmd": func(x exec.Cmd) *exec.Cmd {
			return &x
		}}
)

func init() {
	engine.RegisterModule(OsExecModule{})
}

type OsExecModule struct{}

func (S OsExecModule) Identity() string {
	return "golang/os/exec"
}
func (S OsExecModule) TypeDefine() []byte {
	return OsExecDefine
}
func (S OsExecModule) Exports() map[string]any {
	return OsExecDeclared
}
