// Code generated by define_gene; DO NOT EDIT.
package hex

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/hex"
	_ "github.com/ZenLiuCN/engine/golang/io"
)

var (
	//go:embed encoding_hex.d.ts
	EncodingHexDefine   []byte
	EncodingHexDeclared = map[string]any{
		"encodeToString": hex.EncodeToString,
		"encodedLen":     hex.EncodedLen,
		"ErrLength":      hex.ErrLength,
		"newDecoder":     hex.NewDecoder,
		"decodeString":   hex.DecodeString,
		"decodedLen":     hex.DecodedLen,
		"dump":           hex.Dump,
		"dumper":         hex.Dumper,
		"newEncoder":     hex.NewEncoder,
		"decode":         hex.Decode,
		"encode":         hex.Encode,
	}
)

func init() {
	engine.RegisterModule(EncodingHexModule{})
}

type EncodingHexModule struct{}

func (S EncodingHexModule) Identity() string {
	return "golang/encoding/hex"
}
func (S EncodingHexModule) TypeDefine() []byte {
	return EncodingHexDefine
}
func (S EncodingHexModule) Exports() map[string]any {
	return EncodingHexDeclared
}
