// Code generated by define_gene; DO NOT EDIT.
package mail

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/service/mail/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/mail"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_mail.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceMailDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceMailDeclared = map[string]any{
		"newService": mail.NewService,

		"emptyService":    engine.Empty[mail.Service],
		"emptyRefService": engine.EmptyRefer[mail.Service],
		"refOfService":    engine.ReferOf[mail.Service],
		"unRefService":    engine.UnRefer[mail.Service]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceMailModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceMailModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceMailModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/mail"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceMailModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceMailDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceMailModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceMailDeclared
}
