// Code generated by define_gene; DO NOT EDIT.
package textproto

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/bufio"
	_ "github.com/ZenLiuCN/engine/golang/io"
	"net/textproto"
)

var (
	//go:embed net_textproto.d.ts
	NetTextprotoDefine   []byte
	NetTextprotoDeclared = map[string]any{
		"trimBytes":              textproto.TrimBytes,
		"trimString":             textproto.TrimString,
		"canonicalMIMEHeaderKey": textproto.CanonicalMIMEHeaderKey,
		"dial":                   textproto.Dial,
		"newConn":                textproto.NewConn,
		"newReader":              textproto.NewReader,
		"newWriter":              textproto.NewWriter,

		"emptyPipeline": func() (v textproto.Pipeline) {
			return v
		},
		"refPipeline": func() *textproto.Pipeline {
			var x textproto.Pipeline
			return &x
		},
		"refOfPipeline": func(x textproto.Pipeline) *textproto.Pipeline {
			return &x
		},
		"emptyReader": func() (v textproto.Reader) {
			return v
		},
		"refReader": func() *textproto.Reader {
			var x textproto.Reader
			return &x
		},
		"refOfReader": func(x textproto.Reader) *textproto.Reader {
			return &x
		},
		"emptyWriter": func() (v textproto.Writer) {
			return v
		},
		"refWriter": func() *textproto.Writer {
			var x textproto.Writer
			return &x
		},
		"refOfWriter": func(x textproto.Writer) *textproto.Writer {
			return &x
		},
		"emptyConn": func() (v textproto.Conn) {
			return v
		},
		"refConn": func() *textproto.Conn {
			var x textproto.Conn
			return &x
		},
		"refOfConn": func(x textproto.Conn) *textproto.Conn {
			return &x
		}}
)

func init() {
	engine.RegisterModule(NetTextprotoModule{})
}

type NetTextprotoModule struct{}

func (S NetTextprotoModule) Identity() string {
	return "golang/net/textproto"
}
func (S NetTextprotoModule) TypeDefine() []byte {
	return NetTextprotoDefine
}
func (S NetTextprotoModule) Exports() map[string]any {
	return NetTextprotoDeclared
}
