// Code generated by define_gene; DO NOT EDIT.
package x509

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"crypto/x509"
	_ "github.com/ZenLiuCN/engine/golang/crypto"
	_ "github.com/ZenLiuCN/engine/golang/crypto/ecdsa"
	_ "github.com/ZenLiuCN/engine/golang/crypto/rsa"
	_ "github.com/ZenLiuCN/engine/golang/crypto/x509/pkix"
	_ "github.com/ZenLiuCN/engine/golang/encoding/asn1"
	_ "github.com/ZenLiuCN/engine/golang/encoding/pem"
	_ "github.com/ZenLiuCN/engine/golang/io"
	_ "github.com/ZenLiuCN/engine/golang/math/big"
	_ "github.com/ZenLiuCN/engine/golang/net"
	_ "github.com/ZenLiuCN/engine/golang/net/url"
	_ "github.com/ZenLiuCN/engine/golang/time"
)

var (
	//go:embed crypto_x509.d.ts
	Crypto509Define   []byte
	Crypto509Declared = map[string]any{
		"createCertificate":                         x509.CreateCertificate,
		"encryptPEMBlock":                           x509.EncryptPEMBlock,
		"ExtKeyUsageAny":                            x509.ExtKeyUsageAny,
		"IncompatibleUsage":                         x509.IncompatibleUsage,
		"isEncryptedPEMBlock":                       x509.IsEncryptedPEMBlock,
		"PEMCipherDES":                              x509.PEMCipherDES,
		"RSA":                                       x509.RSA,
		"CANotAuthorizedForExtKeyUsage":             x509.CANotAuthorizedForExtKeyUsage,
		"SHA384WithRSAPSS":                          x509.SHA384WithRSAPSS,
		"decryptPEMBlock":                           x509.DecryptPEMBlock,
		"ExtKeyUsageIPSECEndSystem":                 x509.ExtKeyUsageIPSECEndSystem,
		"marshalPKCS8PrivateKey":                    x509.MarshalPKCS8PrivateKey,
		"marshalPKIXPublicKey":                      x509.MarshalPKIXPublicKey,
		"parseCertificate":                          x509.ParseCertificate,
		"DSAWithSHA256":                             x509.DSAWithSHA256,
		"SHA512WithRSA":                             x509.SHA512WithRSA,
		"ECDSAWithSHA384":                           x509.ECDSAWithSHA384,
		"UnknownSignatureAlgorithm":                 x509.UnknownSignatureAlgorithm,
		"SHA384WithRSA":                             x509.SHA384WithRSA,
		"KeyUsageDecipherOnly":                      x509.KeyUsageDecipherOnly,
		"newCertPool":                               x509.NewCertPool,
		"parseCertificateRequest":                   x509.ParseCertificateRequest,
		"KeyUsageContentCommitment":                 x509.KeyUsageContentCommitment,
		"ExtKeyUsageIPSECUser":                      x509.ExtKeyUsageIPSECUser,
		"ExtKeyUsageMicrosoftServerGatedCrypto":     x509.ExtKeyUsageMicrosoftServerGatedCrypto,
		"ExtKeyUsageOCSPSigning":                    x509.ExtKeyUsageOCSPSigning,
		"ExtKeyUsageTimeStamping":                   x509.ExtKeyUsageTimeStamping,
		"KeyUsageCertSign":                          x509.KeyUsageCertSign,
		"KeyUsageDataEncipherment":                  x509.KeyUsageDataEncipherment,
		"KeyUsageEncipherOnly":                      x509.KeyUsageEncipherOnly,
		"DSA":                                       x509.DSA,
		"NameMismatch":                              x509.NameMismatch,
		"SHA1WithRSA":                               x509.SHA1WithRSA,
		"SHA512WithRSAPSS":                          x509.SHA512WithRSAPSS,
		"marshalECPrivateKey":                       x509.MarshalECPrivateKey,
		"ExtKeyUsageEmailProtection":                x509.ExtKeyUsageEmailProtection,
		"ExtKeyUsageNetscapeServerGatedCrypto":      x509.ExtKeyUsageNetscapeServerGatedCrypto,
		"IncorrectPasswordError":                    x509.IncorrectPasswordError,
		"KeyUsageDigitalSignature":                  x509.KeyUsageDigitalSignature,
		"NameConstraintsWithoutSANs":                x509.NameConstraintsWithoutSANs,
		"PEMCipherAES256":                           x509.PEMCipherAES256,
		"parseCRL":                                  x509.ParseCRL,
		"createRevocationList":                      x509.CreateRevocationList,
		"parsePKCS8PrivateKey":                      x509.ParsePKCS8PrivateKey,
		"UnconstrainedName":                         x509.UnconstrainedName,
		"setFallbackRoots":                          x509.SetFallbackRoots,
		"TooManyIntermediates":                      x509.TooManyIntermediates,
		"ExtKeyUsageCodeSigning":                    x509.ExtKeyUsageCodeSigning,
		"ECDSAWithSHA256":                           x509.ECDSAWithSHA256,
		"ExtKeyUsageClientAuth":                     x509.ExtKeyUsageClientAuth,
		"ExtKeyUsageIPSECTunnel":                    x509.ExtKeyUsageIPSECTunnel,
		"KeyUsageCRLSign":                           x509.KeyUsageCRLSign,
		"parseCertificates":                         x509.ParseCertificates,
		"parseRevocationList":                       x509.ParseRevocationList,
		"systemCertPool":                            x509.SystemCertPool,
		"CANotAuthorizedForThisName":                x509.CANotAuthorizedForThisName,
		"TooManyConstraints":                        x509.TooManyConstraints,
		"ExtKeyUsageMicrosoftKernelCodeSigning":     x509.ExtKeyUsageMicrosoftKernelCodeSigning,
		"KeyUsageKeyAgreement":                      x509.KeyUsageKeyAgreement,
		"MD5WithRSA":                                x509.MD5WithRSA,
		"PEMCipherAES192":                           x509.PEMCipherAES192,
		"ExtKeyUsageMicrosoftCommercialCodeSigning": x509.ExtKeyUsageMicrosoftCommercialCodeSigning,
		"ECDSAWithSHA512":                           x509.ECDSAWithSHA512,
		"marshalPKCS1PublicKey":                     x509.MarshalPKCS1PublicKey,
		"NotAuthorizedToSign":                       x509.NotAuthorizedToSign,
		"SHA256WithRSAPSS":                          x509.SHA256WithRSAPSS,
		"UnknownPublicKeyAlgorithm":                 x509.UnknownPublicKeyAlgorithm,
		"ExtKeyUsageServerAuth":                     x509.ExtKeyUsageServerAuth,
		"parseECPrivateKey":                         x509.ParseECPrivateKey,
		"parsePKCS1PrivateKey":                      x509.ParsePKCS1PrivateKey,
		"parsePKCS1PublicKey":                       x509.ParsePKCS1PublicKey,
		"PureEd25519":                               x509.PureEd25519,
		"SHA256WithRSA":                             x509.SHA256WithRSA,
		"DSAWithSHA1":                               x509.DSAWithSHA1,
		"ECDSAWithSHA1":                             x509.ECDSAWithSHA1,
		"ErrUnsupportedAlgorithm":                   x509.ErrUnsupportedAlgorithm,
		"Expired":                                   x509.Expired,
		"PEMCipherAES128":                           x509.PEMCipherAES128,
		"parseDERCRL":                               x509.ParseDERCRL,
		"ECDSA":                                     x509.ECDSA,
		"Ed25519":                                   x509.Ed25519,
		"KeyUsageKeyEncipherment":                   x509.KeyUsageKeyEncipherment,
		"MD2WithRSA":                                x509.MD2WithRSA,
		"marshalPKCS1PrivateKey":                    x509.MarshalPKCS1PrivateKey,
		"PEMCipher3DES":                             x509.PEMCipher3DES,
		"parsePKIXPublicKey":                        x509.ParsePKIXPublicKey,
		"createCertificateRequest":                  x509.CreateCertificateRequest,

		"emptyVerifyOptions": func() (v x509.VerifyOptions) {
			return v
		},
		"refVerifyOptions": func() *x509.VerifyOptions {
			var x x509.VerifyOptions
			return &x
		},
		"refOfVerifyOptions": func(x x509.VerifyOptions) *x509.VerifyOptions {
			return &x
		},
		"emptyCertPool": func() (v x509.CertPool) {
			return v
		},
		"refCertPool": func() *x509.CertPool {
			var x x509.CertPool
			return &x
		},
		"refOfCertPool": func(x x509.CertPool) *x509.CertPool {
			return &x
		},
		"emptyRevocationListEntry": func() (v x509.RevocationListEntry) {
			return v
		},
		"refRevocationListEntry": func() *x509.RevocationListEntry {
			var x x509.RevocationListEntry
			return &x
		},
		"refOfRevocationListEntry": func(x x509.RevocationListEntry) *x509.RevocationListEntry {
			return &x
		},
		"emptyCertificateRequest": func() (v x509.CertificateRequest) {
			return v
		},
		"refCertificateRequest": func() *x509.CertificateRequest {
			var x x509.CertificateRequest
			return &x
		},
		"refOfCertificateRequest": func(x x509.CertificateRequest) *x509.CertificateRequest {
			return &x
		},
		"emptyRevocationList": func() (v x509.RevocationList) {
			return v
		},
		"refRevocationList": func() *x509.RevocationList {
			var x x509.RevocationList
			return &x
		},
		"refOfRevocationList": func(x x509.RevocationList) *x509.RevocationList {
			return &x
		},
		"emptyUnhandledCriticalExtension": func() (v x509.UnhandledCriticalExtension) {
			return v
		},
		"refUnhandledCriticalExtension": func() *x509.UnhandledCriticalExtension {
			var x x509.UnhandledCriticalExtension
			return &x
		},
		"refOfUnhandledCriticalExtension": func(x x509.UnhandledCriticalExtension) *x509.UnhandledCriticalExtension {
			return &x
		},
		"emptyCertificate": func() (v x509.Certificate) {
			return v
		},
		"refCertificate": func() *x509.Certificate {
			var x x509.Certificate
			return &x
		},
		"refOfCertificate": func(x x509.Certificate) *x509.Certificate {
			return &x
		}}
)

func init() {
	engine.RegisterModule(Crypto509Module{})
}

type Crypto509Module struct{}

func (S Crypto509Module) Identity() string {
	return "golang/crypto/x509"
}
func (S Crypto509Module) TypeDefine() []byte {
	return Crypto509Define
}
func (S Crypto509Module) Exports() map[string]any {
	return Crypto509Declared
}
