// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection
// Code generated by define_gene; DO NOT EDIT.


declare module 'golang/syscall' {

    // @ts-ignore
    import * as sync from 'golang/sync'
    // @ts-ignore
    import type { bool,byte,error,GoError,int,int16,int32,int64,int8,Ref,Struct,uint,uint16,uint32,uint64,uint8,uintptr } from 'go'

    export interface Errno extends uintptr, GoError {

        error(): string

        is(target: error): bool

        temporary(): bool

        timeout(): bool
    }

    export interface Handle extends uintptr {

    }

    export interface Sockaddr {

    }

    export interface Conn {

        syscallConn(): RawConn
    }

    export interface SecurityAttributes extends Struct<SecurityAttributes> {

        length: uint32
        securityDescriptor: uintptr
        inheritHandle: uint32
    }

    export interface SysProcAttr extends Struct<SysProcAttr> {

        hideWindow: bool
        cmdLine: string
        creationFlags: uint32
        processAttributes: Ref<SecurityAttributes>
        threadAttributes: Ref<SecurityAttributes>
        noInheritHandles: bool
        additionalInheritedHandles: Handle[]
        parentProcess: Handle
    }

    export interface RawConn {

        control(v1: (fd: uintptr) => void)/*error*/
        read(v1: (fd: uintptr) => boolean)/*error*/
        write(v1: (fd: uintptr) => boolean)/*error*/
    }

}
