// Code generated by define_gene; DO NOT EDIT.
package binary

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/binary"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
)

var (
	//go:embed encoding_binary.d.ts
	EncodingBinaryDefine   []byte
	EncodingBinaryDeclared = map[string]any{
		"MaxVarintLen32": binary.MaxVarintLen32,
		"size":           binary.Size,
		"appendUvarint":  binary.AppendUvarint,
		"BigEndian":      binary.BigEndian,
		"LittleEndian":   binary.LittleEndian,
		"readVarint":     binary.ReadVarint,
		"uvarint":        binary.Uvarint,
		"appendVarint":   binary.AppendVarint,
		"MaxVarintLen16": binary.MaxVarintLen16,
		"readUvarint":    binary.ReadUvarint,
		"NativeEndian":   binary.NativeEndian,
		"putUvarint":     binary.PutUvarint,
		"varint":         binary.Varint,
		"write":          binary.Write,
		"MaxVarintLen64": binary.MaxVarintLen64,
		"putVarint":      binary.PutVarint,
		"read":           binary.Read,
	}
)

func init() {
	engine.RegisterModule(EncodingBinaryModule{})
}

type EncodingBinaryModule struct{}

func (S EncodingBinaryModule) Identity() string {
	return "golang/encoding/binary"
}
func (S EncodingBinaryModule) TypeDefine() []byte {
	return EncodingBinaryDefine
}
func (S EncodingBinaryModule) Exports() map[string]any {
	return EncodingBinaryDeclared
}
