// Code generated by define_gene; DO NOT EDIT.
package bits

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"math/bits"
)

var (
	//go:embed math_bits.d.ts
	MathBitsDefine   []byte
	MathBitsDeclared = map[string]any{
		"rotateLeft8":     bits.RotateLeft8,
		"sub":             bits.Sub,
		"add32":           bits.Add32,
		"leadingZeros32":  bits.LeadingZeros32,
		"mul64":           bits.Mul64,
		"reverse":         bits.Reverse,
		"rotateLeft16":    bits.RotateLeft16,
		"onesCount8":      bits.OnesCount8,
		"len32":           bits.Len32,
		"mul32":           bits.Mul32,
		"sub64":           bits.Sub64,
		"UintSize":        bits.UintSize,
		"div64":           bits.Div64,
		"rem64":           bits.Rem64,
		"reverseBytes32":  bits.ReverseBytes32,
		"reverse16":       bits.Reverse16,
		"reverse64":       bits.Reverse64,
		"reverseBytes64":  bits.ReverseBytes64,
		"trailingZeros8":  bits.TrailingZeros8,
		"reverseBytes16":  bits.ReverseBytes16,
		"onesCount16":     bits.OnesCount16,
		"rotateLeft32":    bits.RotateLeft32,
		"rem32":           bits.Rem32,
		"trailingZeros16": bits.TrailingZeros16,
		"trailingZeros32": bits.TrailingZeros32,
		"len16":           bits.Len16,
		"add64":           bits.Add64,
		"leadingZeros16":  bits.LeadingZeros16,
		"leadingZeros64":  bits.LeadingZeros64,
		"leadingZeros":    bits.LeadingZeros,
		"trailingZeros":   bits.TrailingZeros,
		"leadingZeros8":   bits.LeadingZeros8,
		"onesCount":       bits.OnesCount,
		"rotateLeft":      bits.RotateLeft,
		"sub32":           bits.Sub32,
		"trailingZeros64": bits.TrailingZeros64,
		"len64":           bits.Len64,
		"onesCount32":     bits.OnesCount32,
		"reverse32":       bits.Reverse32,
		"rotateLeft64":    bits.RotateLeft64,
		"add":             bits.Add,
		"len":             bits.Len,
		"reverseBytes":    bits.ReverseBytes,
		"onesCount64":     bits.OnesCount64,
		"rem":             bits.Rem,
		"reverse8":        bits.Reverse8,
		"div32":           bits.Div32,
		"len8":            bits.Len8,
		"mul":             bits.Mul,
		"div":             bits.Div,
	}
)

func init() {
	engine.RegisterModule(MathBitsModule{})
}

type MathBitsModule struct{}

func (S MathBitsModule) Identity() string {
	return "golang/math/bits"
}
func (S MathBitsModule) TypeDefine() []byte {
	return MathBitsDefine
}
func (S MathBitsModule) Exports() map[string]any {
	return MathBitsDeclared
}
