// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection
// Code generated by define_gene; DO NOT EDIT.
declare module 'golang/encoding/pem'{

	// @ts-ignore
	import * as io from 'golang/io'
	// @ts-ignore
	import type {map,Struct,Ref,error} from 'go'
	export interface Block extends Struct<Block>{

			type:string
			headers:map<string,string>
			bytes:Uint8Array
	}
	export function decode(data:Uint8Array):[Ref<Block>,Uint8Array]

	export function encode(out:io.Writer,b:Ref<Block>)/*error*/

	export function encodeToMemory(b:Ref<Block>):Uint8Array

	export function emptyBlock():Block
	export function emptyRefBlock():Ref<Block>
	export function refOfBlock(x:Block,v:Ref<Block>)
	export function unRefBlock(v:Ref<Block>):Block
}