// Code generated by define_gene; DO NOT EDIT.
package pem

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/pem"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
)

var (
	//go:embed encoding_pem.d.ts
	EncodingPemDefine   []byte
	EncodingPemDeclared = map[string]any{
		"decode":         pem.Decode,
		"encode":         pem.Encode,
		"encodeToMemory": pem.EncodeToMemory,

		"emptyBlock":    engine.Empty[pem.Block],
		"emptyRefBlock": engine.EmptyRefer[pem.Block],
		"refOfBlock":    engine.ReferOf[pem.Block],
		"unRefBlock":    engine.UnRefer[pem.Block]}
)

func init() {
	engine.RegisterModule(EncodingPemModule{})
}

type EncodingPemModule struct{}

func (S EncodingPemModule) Identity() string {
	return "golang/encoding/pem"
}
func (S EncodingPemModule) TypeDefine() []byte {
	return EncodingPemDefine
}
func (S EncodingPemModule) Exports() map[string]any {
	return EncodingPemDeclared
}
