// Code generated by define_gene; DO NOT EDIT.
package fmt

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"fmt"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
)

var (
	//go:embed fmt.d.ts
	FmtDefine   []byte
	FmtDeclared = map[string]any{
		"appendln":     fmt.Appendln,
		"fprintf":      fmt.Fprintf,
		"fprintln":     fmt.Fprintln,
		"print":        fmt.Print,
		"scanln":       fmt.Scanln,
		"append":       fmt.Append,
		"errorf":       fmt.Errorf,
		"fscanln":      fmt.Fscanln,
		"printf":       fmt.Printf,
		"sprint":       fmt.Sprint,
		"sprintf":      fmt.Sprintf,
		"appendf":      fmt.Appendf,
		"fscanf":       fmt.Fscanf,
		"println":      fmt.Println,
		"sprintln":     fmt.Sprintln,
		"sscan":        fmt.Sscan,
		"sscanln":      fmt.Sscanln,
		"fscan":        fmt.Fscan,
		"fprint":       fmt.Fprint,
		"scan":         fmt.Scan,
		"scanf":        fmt.Scanf,
		"sscanf":       fmt.Sscanf,
		"formatString": fmt.FormatString,
	}
)

func init() {
	engine.RegisterModule(FmtModule{})
}

type FmtModule struct{}

func (S FmtModule) Identity() string {
	return "golang/fmt"
}
func (S FmtModule) TypeDefine() []byte {
	return FmtDefine
}
func (S FmtModule) Exports() map[string]any {
	return FmtDeclared
}
