// Code generated by define_gene; DO NOT EDIT.
package larkreport

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/context"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/report/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_report_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceReport1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceReport1Declared = map[string]any{
		"UserIdTypeQueryTaskUnionId":          larkreport.UserIdTypeQueryTaskUnionId,
		"IncludeDeletedExclude":               larkreport.IncludeDeletedExclude,
		"newFormFieldBuilder":                 larkreport.NewFormFieldBuilder,
		"newQueryTaskPathReqBodyBuilder":      larkreport.NewQueryTaskPathReqBodyBuilder,
		"newQueryTaskReqBuilder":              larkreport.NewQueryTaskReqBuilder,
		"newRuleBuilder":                      larkreport.NewRuleBuilder,
		"UserIdTypeQueryTaskUserId":           larkreport.UserIdTypeQueryTaskUserId,
		"UserIdTypeUnionId":                   larkreport.UserIdTypeUnionId,
		"UserIdTypeUserId":                    larkreport.UserIdTypeUserId,
		"New":                                 larkreport.New,
		"newFormContentBuilder":               larkreport.NewFormContentBuilder,
		"newQueryTaskReqBodyBuilder":          larkreport.NewQueryTaskReqBodyBuilder,
		"newQueryRuleReqBuilder":              larkreport.NewQueryRuleReqBuilder,
		"newRemoveRuleViewReqBodyBuilder":     larkreport.NewRemoveRuleViewReqBodyBuilder,
		"UserIdTypeRemoveRuleViewUserId":      larkreport.UserIdTypeRemoveRuleViewUserId,
		"newRemoveRuleViewReqBuilder":         larkreport.NewRemoveRuleViewReqBuilder,
		"newTaskBuilder":                      larkreport.NewTaskBuilder,
		"UserIdTypeOpenId":                    larkreport.UserIdTypeOpenId,
		"UserIdTypeQueryTaskOpenId":           larkreport.UserIdTypeQueryTaskOpenId,
		"UserIdTypeRemoveRuleViewOpenId":      larkreport.UserIdTypeRemoveRuleViewOpenId,
		"IncludeDeletedInclude":               larkreport.IncludeDeletedInclude,
		"newDepartmentIdBuilder":              larkreport.NewDepartmentIdBuilder,
		"newRemoveRuleViewPathReqBodyBuilder": larkreport.NewRemoveRuleViewPathReqBodyBuilder,
		"UserIdTypeRemoveRuleViewUnionId":     larkreport.UserIdTypeRemoveRuleViewUnionId,

		"emptyDepartmentId":                        engine.Empty[larkreport.DepartmentId],
		"emptyRefDepartmentId":                     engine.EmptyRefer[larkreport.DepartmentId],
		"refOfDepartmentId":                        engine.ReferOf[larkreport.DepartmentId],
		"unRefDepartmentId":                        engine.UnRefer[larkreport.DepartmentId],
		"emptyFormContentBuilder":                  engine.Empty[larkreport.FormContentBuilder],
		"emptyRefFormContentBuilder":               engine.EmptyRefer[larkreport.FormContentBuilder],
		"refOfFormContentBuilder":                  engine.ReferOf[larkreport.FormContentBuilder],
		"unRefFormContentBuilder":                  engine.UnRefer[larkreport.FormContentBuilder],
		"emptyFormField":                           engine.Empty[larkreport.FormField],
		"emptyRefFormField":                        engine.EmptyRefer[larkreport.FormField],
		"refOfFormField":                           engine.ReferOf[larkreport.FormField],
		"unRefFormField":                           engine.UnRefer[larkreport.FormField],
		"emptyQueryRuleResp":                       engine.Empty[larkreport.QueryRuleResp],
		"emptyRefQueryRuleResp":                    engine.EmptyRefer[larkreport.QueryRuleResp],
		"refOfQueryRuleResp":                       engine.ReferOf[larkreport.QueryRuleResp],
		"unRefQueryRuleResp":                       engine.UnRefer[larkreport.QueryRuleResp],
		"emptyQueryTaskPathReqBodyBuilder":         engine.Empty[larkreport.QueryTaskPathReqBodyBuilder],
		"emptyRefQueryTaskPathReqBodyBuilder":      engine.EmptyRefer[larkreport.QueryTaskPathReqBodyBuilder],
		"refOfQueryTaskPathReqBodyBuilder":         engine.ReferOf[larkreport.QueryTaskPathReqBodyBuilder],
		"unRefQueryTaskPathReqBodyBuilder":         engine.UnRefer[larkreport.QueryTaskPathReqBodyBuilder],
		"emptyQueryTaskRespData":                   engine.Empty[larkreport.QueryTaskRespData],
		"emptyRefQueryTaskRespData":                engine.EmptyRefer[larkreport.QueryTaskRespData],
		"refOfQueryTaskRespData":                   engine.ReferOf[larkreport.QueryTaskRespData],
		"unRefQueryTaskRespData":                   engine.UnRefer[larkreport.QueryTaskRespData],
		"emptyRemoveRuleViewReqBodyBuilder":        engine.Empty[larkreport.RemoveRuleViewReqBodyBuilder],
		"emptyRefRemoveRuleViewReqBodyBuilder":     engine.EmptyRefer[larkreport.RemoveRuleViewReqBodyBuilder],
		"refOfRemoveRuleViewReqBodyBuilder":        engine.ReferOf[larkreport.RemoveRuleViewReqBodyBuilder],
		"unRefRemoveRuleViewReqBodyBuilder":        engine.UnRefer[larkreport.RemoveRuleViewReqBodyBuilder],
		"emptyRemoveRuleViewResp":                  engine.Empty[larkreport.RemoveRuleViewResp],
		"emptyRefRemoveRuleViewResp":               engine.EmptyRefer[larkreport.RemoveRuleViewResp],
		"refOfRemoveRuleViewResp":                  engine.ReferOf[larkreport.RemoveRuleViewResp],
		"unRefRemoveRuleViewResp":                  engine.UnRefer[larkreport.RemoveRuleViewResp],
		"emptyDepartmentIdBuilder":                 engine.Empty[larkreport.DepartmentIdBuilder],
		"emptyRefDepartmentIdBuilder":              engine.EmptyRefer[larkreport.DepartmentIdBuilder],
		"refOfDepartmentIdBuilder":                 engine.ReferOf[larkreport.DepartmentIdBuilder],
		"unRefDepartmentIdBuilder":                 engine.UnRefer[larkreport.DepartmentIdBuilder],
		"emptyFormFieldBuilder":                    engine.Empty[larkreport.FormFieldBuilder],
		"emptyRefFormFieldBuilder":                 engine.EmptyRefer[larkreport.FormFieldBuilder],
		"refOfFormFieldBuilder":                    engine.ReferOf[larkreport.FormFieldBuilder],
		"unRefFormFieldBuilder":                    engine.UnRefer[larkreport.FormFieldBuilder],
		"emptyQueryTaskReqBody":                    engine.Empty[larkreport.QueryTaskReqBody],
		"emptyRefQueryTaskReqBody":                 engine.EmptyRefer[larkreport.QueryTaskReqBody],
		"refOfQueryTaskReqBody":                    engine.ReferOf[larkreport.QueryTaskReqBody],
		"unRefQueryTaskReqBody":                    engine.UnRefer[larkreport.QueryTaskReqBody],
		"emptyRemoveRuleViewReq":                   engine.Empty[larkreport.RemoveRuleViewReq],
		"emptyRefRemoveRuleViewReq":                engine.EmptyRefer[larkreport.RemoveRuleViewReq],
		"refOfRemoveRuleViewReq":                   engine.ReferOf[larkreport.RemoveRuleViewReq],
		"unRefRemoveRuleViewReq":                   engine.UnRefer[larkreport.RemoveRuleViewReq],
		"emptyRemoveRuleViewReqBuilder":            engine.Empty[larkreport.RemoveRuleViewReqBuilder],
		"emptyRefRemoveRuleViewReqBuilder":         engine.EmptyRefer[larkreport.RemoveRuleViewReqBuilder],
		"refOfRemoveRuleViewReqBuilder":            engine.ReferOf[larkreport.RemoveRuleViewReqBuilder],
		"unRefRemoveRuleViewReqBuilder":            engine.UnRefer[larkreport.RemoveRuleViewReqBuilder],
		"emptyQueryRuleReq":                        engine.Empty[larkreport.QueryRuleReq],
		"emptyRefQueryRuleReq":                     engine.EmptyRefer[larkreport.QueryRuleReq],
		"refOfQueryRuleReq":                        engine.ReferOf[larkreport.QueryRuleReq],
		"unRefQueryRuleReq":                        engine.UnRefer[larkreport.QueryRuleReq],
		"emptyRemoveRuleViewReqBody":               engine.Empty[larkreport.RemoveRuleViewReqBody],
		"emptyRefRemoveRuleViewReqBody":            engine.EmptyRefer[larkreport.RemoveRuleViewReqBody],
		"refOfRemoveRuleViewReqBody":               engine.ReferOf[larkreport.RemoveRuleViewReqBody],
		"unRefRemoveRuleViewReqBody":               engine.UnRefer[larkreport.RemoveRuleViewReqBody],
		"emptyQueryTaskReq":                        engine.Empty[larkreport.QueryTaskReq],
		"emptyRefQueryTaskReq":                     engine.EmptyRefer[larkreport.QueryTaskReq],
		"refOfQueryTaskReq":                        engine.ReferOf[larkreport.QueryTaskReq],
		"unRefQueryTaskReq":                        engine.UnRefer[larkreport.QueryTaskReq],
		"emptyQueryTaskResp":                       engine.Empty[larkreport.QueryTaskResp],
		"emptyRefQueryTaskResp":                    engine.EmptyRefer[larkreport.QueryTaskResp],
		"refOfQueryTaskResp":                       engine.ReferOf[larkreport.QueryTaskResp],
		"unRefQueryTaskResp":                       engine.UnRefer[larkreport.QueryTaskResp],
		"emptyRule":                                engine.Empty[larkreport.Rule],
		"emptyRefRule":                             engine.EmptyRefer[larkreport.Rule],
		"refOfRule":                                engine.ReferOf[larkreport.Rule],
		"unRefRule":                                engine.UnRefer[larkreport.Rule],
		"emptyV1":                                  engine.Empty[larkreport.V1],
		"emptyRefV1":                               engine.EmptyRefer[larkreport.V1],
		"refOfV1":                                  engine.ReferOf[larkreport.V1],
		"unRefV1":                                  engine.UnRefer[larkreport.V1],
		"emptyQueryTaskReqBodyBuilder":             engine.Empty[larkreport.QueryTaskReqBodyBuilder],
		"emptyRefQueryTaskReqBodyBuilder":          engine.EmptyRefer[larkreport.QueryTaskReqBodyBuilder],
		"refOfQueryTaskReqBodyBuilder":             engine.ReferOf[larkreport.QueryTaskReqBodyBuilder],
		"unRefQueryTaskReqBodyBuilder":             engine.UnRefer[larkreport.QueryTaskReqBodyBuilder],
		"emptyQueryTaskReqBuilder":                 engine.Empty[larkreport.QueryTaskReqBuilder],
		"emptyRefQueryTaskReqBuilder":              engine.EmptyRefer[larkreport.QueryTaskReqBuilder],
		"refOfQueryTaskReqBuilder":                 engine.ReferOf[larkreport.QueryTaskReqBuilder],
		"unRefQueryTaskReqBuilder":                 engine.UnRefer[larkreport.QueryTaskReqBuilder],
		"emptyTaskBuilder":                         engine.Empty[larkreport.TaskBuilder],
		"emptyRefTaskBuilder":                      engine.EmptyRefer[larkreport.TaskBuilder],
		"refOfTaskBuilder":                         engine.ReferOf[larkreport.TaskBuilder],
		"unRefTaskBuilder":                         engine.UnRefer[larkreport.TaskBuilder],
		"emptyFormContent":                         engine.Empty[larkreport.FormContent],
		"emptyRefFormContent":                      engine.EmptyRefer[larkreport.FormContent],
		"refOfFormContent":                         engine.ReferOf[larkreport.FormContent],
		"unRefFormContent":                         engine.UnRefer[larkreport.FormContent],
		"emptyQueryRuleReqBuilder":                 engine.Empty[larkreport.QueryRuleReqBuilder],
		"emptyRefQueryRuleReqBuilder":              engine.EmptyRefer[larkreport.QueryRuleReqBuilder],
		"refOfQueryRuleReqBuilder":                 engine.ReferOf[larkreport.QueryRuleReqBuilder],
		"unRefQueryRuleReqBuilder":                 engine.UnRefer[larkreport.QueryRuleReqBuilder],
		"emptyQueryRuleRespData":                   engine.Empty[larkreport.QueryRuleRespData],
		"emptyRefQueryRuleRespData":                engine.EmptyRefer[larkreport.QueryRuleRespData],
		"refOfQueryRuleRespData":                   engine.ReferOf[larkreport.QueryRuleRespData],
		"unRefQueryRuleRespData":                   engine.UnRefer[larkreport.QueryRuleRespData],
		"emptyRemoveRuleViewPathReqBodyBuilder":    engine.Empty[larkreport.RemoveRuleViewPathReqBodyBuilder],
		"emptyRefRemoveRuleViewPathReqBodyBuilder": engine.EmptyRefer[larkreport.RemoveRuleViewPathReqBodyBuilder],
		"refOfRemoveRuleViewPathReqBodyBuilder":    engine.ReferOf[larkreport.RemoveRuleViewPathReqBodyBuilder],
		"unRefRemoveRuleViewPathReqBodyBuilder":    engine.UnRefer[larkreport.RemoveRuleViewPathReqBodyBuilder],
		"emptyRuleBuilder":                         engine.Empty[larkreport.RuleBuilder],
		"emptyRefRuleBuilder":                      engine.EmptyRefer[larkreport.RuleBuilder],
		"refOfRuleBuilder":                         engine.ReferOf[larkreport.RuleBuilder],
		"unRefRuleBuilder":                         engine.UnRefer[larkreport.RuleBuilder],
		"emptyTask":                                engine.Empty[larkreport.Task],
		"emptyRefTask":                             engine.EmptyRefer[larkreport.Task],
		"refOfTask":                                engine.ReferOf[larkreport.Task],
		"unRefTask":                                engine.UnRefer[larkreport.Task]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceReport1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceReport1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/report/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceReport1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceReport1Declared
}
