// Code generated by define_gene; DO NOT EDIT.
package larkreport

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	"github.com/larksuite/oapi-sdk-go/v3/service/report/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_report_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceReport1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceReport1Declared = map[string]any{
		"UserIdTypeRemoveRuleViewOpenId":      larkreport.UserIdTypeRemoveRuleViewOpenId,
		"UserIdTypeRemoveRuleViewUnionId":     larkreport.UserIdTypeRemoveRuleViewUnionId,
		"newFormContentBuilder":               larkreport.NewFormContentBuilder,
		"newQueryTaskReqBodyBuilder":          larkreport.NewQueryTaskReqBodyBuilder,
		"newRemoveRuleViewPathReqBodyBuilder": larkreport.NewRemoveRuleViewPathReqBodyBuilder,
		"newRuleBuilder":                      larkreport.NewRuleBuilder,
		"IncludeDeletedExclude":               larkreport.IncludeDeletedExclude,
		"newDepartmentIdBuilder":              larkreport.NewDepartmentIdBuilder,
		"newQueryTaskReqBuilder":              larkreport.NewQueryTaskReqBuilder,
		"newTaskBuilder":                      larkreport.NewTaskBuilder,
		"UserIdTypeQueryTaskUserId":           larkreport.UserIdTypeQueryTaskUserId,
		"IncludeDeletedInclude":               larkreport.IncludeDeletedInclude,
		"newFormFieldBuilder":                 larkreport.NewFormFieldBuilder,
		"newQueryRuleReqBuilder":              larkreport.NewQueryRuleReqBuilder,
		"newRemoveRuleViewReqBodyBuilder":     larkreport.NewRemoveRuleViewReqBodyBuilder,
		"UserIdTypeQueryTaskOpenId":           larkreport.UserIdTypeQueryTaskOpenId,
		"UserIdTypeQueryTaskUnionId":          larkreport.UserIdTypeQueryTaskUnionId,
		"UserIdTypeRemoveRuleViewUserId":      larkreport.UserIdTypeRemoveRuleViewUserId,
		"UserIdTypeUnionId":                   larkreport.UserIdTypeUnionId,
		"New":                                 larkreport.New,
		"newQueryTaskPathReqBodyBuilder":      larkreport.NewQueryTaskPathReqBodyBuilder,
		"newRemoveRuleViewReqBuilder":         larkreport.NewRemoveRuleViewReqBuilder,
		"UserIdTypeOpenId":                    larkreport.UserIdTypeOpenId,
		"UserIdTypeUserId":                    larkreport.UserIdTypeUserId,

		"emptyFormContent":              engine.Empty[larkreport.FormContent],
		"emptyRefFormContent":           engine.EmptyRefer[larkreport.FormContent],
		"refOfFormContent":              engine.ReferOf[larkreport.FormContent],
		"unRefFormContent":              engine.UnRefer[larkreport.FormContent],
		"emptyFormField":                engine.Empty[larkreport.FormField],
		"emptyRefFormField":             engine.EmptyRefer[larkreport.FormField],
		"refOfFormField":                engine.ReferOf[larkreport.FormField],
		"unRefFormField":                engine.UnRefer[larkreport.FormField],
		"emptyQueryTaskRespData":        engine.Empty[larkreport.QueryTaskRespData],
		"emptyRefQueryTaskRespData":     engine.EmptyRefer[larkreport.QueryTaskRespData],
		"refOfQueryTaskRespData":        engine.ReferOf[larkreport.QueryTaskRespData],
		"unRefQueryTaskRespData":        engine.UnRefer[larkreport.QueryTaskRespData],
		"emptyDepartmentId":             engine.Empty[larkreport.DepartmentId],
		"emptyRefDepartmentId":          engine.EmptyRefer[larkreport.DepartmentId],
		"refOfDepartmentId":             engine.ReferOf[larkreport.DepartmentId],
		"unRefDepartmentId":             engine.UnRefer[larkreport.DepartmentId],
		"emptyQueryRuleResp":            engine.Empty[larkreport.QueryRuleResp],
		"emptyRefQueryRuleResp":         engine.EmptyRefer[larkreport.QueryRuleResp],
		"refOfQueryRuleResp":            engine.ReferOf[larkreport.QueryRuleResp],
		"unRefQueryRuleResp":            engine.UnRefer[larkreport.QueryRuleResp],
		"emptyQueryTaskReq":             engine.Empty[larkreport.QueryTaskReq],
		"emptyRefQueryTaskReq":          engine.EmptyRefer[larkreport.QueryTaskReq],
		"refOfQueryTaskReq":             engine.ReferOf[larkreport.QueryTaskReq],
		"unRefQueryTaskReq":             engine.UnRefer[larkreport.QueryTaskReq],
		"emptyRemoveRuleViewReqBody":    engine.Empty[larkreport.RemoveRuleViewReqBody],
		"emptyRefRemoveRuleViewReqBody": engine.EmptyRefer[larkreport.RemoveRuleViewReqBody],
		"refOfRemoveRuleViewReqBody":    engine.ReferOf[larkreport.RemoveRuleViewReqBody],
		"unRefRemoveRuleViewReqBody":    engine.UnRefer[larkreport.RemoveRuleViewReqBody],
		"emptyQueryRuleRespData":        engine.Empty[larkreport.QueryRuleRespData],
		"emptyRefQueryRuleRespData":     engine.EmptyRefer[larkreport.QueryRuleRespData],
		"refOfQueryRuleRespData":        engine.ReferOf[larkreport.QueryRuleRespData],
		"unRefQueryRuleRespData":        engine.UnRefer[larkreport.QueryRuleRespData],
		"emptyTask":                     engine.Empty[larkreport.Task],
		"emptyRefTask":                  engine.EmptyRefer[larkreport.Task],
		"refOfTask":                     engine.ReferOf[larkreport.Task],
		"unRefTask":                     engine.UnRefer[larkreport.Task],
		"emptyV1":                       engine.Empty[larkreport.V1],
		"emptyRefV1":                    engine.EmptyRefer[larkreport.V1],
		"refOfV1":                       engine.ReferOf[larkreport.V1],
		"unRefV1":                       engine.UnRefer[larkreport.V1],
		"emptyQueryRuleReq":             engine.Empty[larkreport.QueryRuleReq],
		"emptyRefQueryRuleReq":          engine.EmptyRefer[larkreport.QueryRuleReq],
		"refOfQueryRuleReq":             engine.ReferOf[larkreport.QueryRuleReq],
		"unRefQueryRuleReq":             engine.UnRefer[larkreport.QueryRuleReq],
		"emptyRemoveRuleViewResp":       engine.Empty[larkreport.RemoveRuleViewResp],
		"emptyRefRemoveRuleViewResp":    engine.EmptyRefer[larkreport.RemoveRuleViewResp],
		"refOfRemoveRuleViewResp":       engine.ReferOf[larkreport.RemoveRuleViewResp],
		"unRefRemoveRuleViewResp":       engine.UnRefer[larkreport.RemoveRuleViewResp],
		"emptyRule":                     engine.Empty[larkreport.Rule],
		"emptyRefRule":                  engine.EmptyRefer[larkreport.Rule],
		"refOfRule":                     engine.ReferOf[larkreport.Rule],
		"unRefRule":                     engine.UnRefer[larkreport.Rule],
		"emptyQueryTaskReqBody":         engine.Empty[larkreport.QueryTaskReqBody],
		"emptyRefQueryTaskReqBody":      engine.EmptyRefer[larkreport.QueryTaskReqBody],
		"refOfQueryTaskReqBody":         engine.ReferOf[larkreport.QueryTaskReqBody],
		"unRefQueryTaskReqBody":         engine.UnRefer[larkreport.QueryTaskReqBody],
		"emptyQueryTaskResp":            engine.Empty[larkreport.QueryTaskResp],
		"emptyRefQueryTaskResp":         engine.EmptyRefer[larkreport.QueryTaskResp],
		"refOfQueryTaskResp":            engine.ReferOf[larkreport.QueryTaskResp],
		"unRefQueryTaskResp":            engine.UnRefer[larkreport.QueryTaskResp],
		"emptyRemoveRuleViewReq":        engine.Empty[larkreport.RemoveRuleViewReq],
		"emptyRefRemoveRuleViewReq":     engine.EmptyRefer[larkreport.RemoveRuleViewReq],
		"refOfRemoveRuleViewReq":        engine.ReferOf[larkreport.RemoveRuleViewReq],
		"unRefRemoveRuleViewReq":        engine.UnRefer[larkreport.RemoveRuleViewReq]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceReport1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceReport1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/report/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceReport1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceReport1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceReport1Declared
}
