// Code generated by define_gene; DO NOT EDIT.
package okr

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/service/okr/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/okr"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_okr.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceOkrDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceOkrDeclared = map[string]any{
		"newService": okr.NewService,
	}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceOkrModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceOkrModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceOkrModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/okr"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceOkrModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceOkrDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceOkrModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceOkrDeclared
}
