// Code generated by define_gene; DO NOT EDIT.
package attendance

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/service/attendance/v1"
	"github.com/larksuite/oapi-sdk-go/v3/service/attendance"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_attendance.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceAttendanceDefine   []byte
	GithubComLarksuiteOapiSdkGo3ServiceAttendanceDeclared = map[string]any{
		"newService": attendance.NewService,
	}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceAttendanceModule{})
}

type GithubComLarksuiteOapiSdkGo3ServiceAttendanceModule struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceAttendanceModule) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/attendance"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceAttendanceModule) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceAttendanceDefine
}
func (S GithubComLarksuiteOapiSdkGo3ServiceAttendanceModule) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceAttendanceDeclared
}
