// Code generated by define_gene; DO NOT EDIT.
package larkverification

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	_ "github.com/ZenLiuCN/engine/modules/golang/context"
	"github.com/larksuite/oapi-sdk-go/v3/service/verification/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_verification_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServiceVerification1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServiceVerification1Declared = map[string]any{
		"New":                          larkverification.New,
		"newDepartmentIdBuilder":       larkverification.NewDepartmentIdBuilder,
		"newVerificationBuilder":       larkverification.NewVerificationBuilder,
		"newVerificationDetailBuilder": larkverification.NewVerificationDetailBuilder,

		"emptyGetVerificationResp":        engine.Empty[larkverification.GetVerificationResp],
		"emptyRefGetVerificationResp":     engine.EmptyRefer[larkverification.GetVerificationResp],
		"refOfGetVerificationResp":        engine.ReferOf[larkverification.GetVerificationResp],
		"unRefGetVerificationResp":        engine.UnRefer[larkverification.GetVerificationResp],
		"emptyVerificationDetail":         engine.Empty[larkverification.VerificationDetail],
		"emptyRefVerificationDetail":      engine.EmptyRefer[larkverification.VerificationDetail],
		"refOfVerificationDetail":         engine.ReferOf[larkverification.VerificationDetail],
		"unRefVerificationDetail":         engine.UnRefer[larkverification.VerificationDetail],
		"emptyDepartmentId":               engine.Empty[larkverification.DepartmentId],
		"emptyRefDepartmentId":            engine.EmptyRefer[larkverification.DepartmentId],
		"refOfDepartmentId":               engine.ReferOf[larkverification.DepartmentId],
		"unRefDepartmentId":               engine.UnRefer[larkverification.DepartmentId],
		"emptyGetVerificationRespData":    engine.Empty[larkverification.GetVerificationRespData],
		"emptyRefGetVerificationRespData": engine.EmptyRefer[larkverification.GetVerificationRespData],
		"refOfGetVerificationRespData":    engine.ReferOf[larkverification.GetVerificationRespData],
		"unRefGetVerificationRespData":    engine.UnRefer[larkverification.GetVerificationRespData],
		"emptyV1":                         engine.Empty[larkverification.V1],
		"emptyRefV1":                      engine.EmptyRefer[larkverification.V1],
		"refOfV1":                         engine.ReferOf[larkverification.V1],
		"unRefV1":                         engine.UnRefer[larkverification.V1],
		"emptyVerification":               engine.Empty[larkverification.Verification],
		"emptyRefVerification":            engine.EmptyRefer[larkverification.Verification],
		"refOfVerification":               engine.ReferOf[larkverification.Verification],
		"unRefVerification":               engine.UnRefer[larkverification.Verification]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServiceVerification1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServiceVerification1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServiceVerification1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/verification/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServiceVerification1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServiceVerification1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServiceVerification1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServiceVerification1Declared
}
