// Code generated by define_gene; DO NOT EDIT.
package gob

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	"encoding/gob"
	_ "github.com/ZenLiuCN/engine/modules/golang/io"
	_ "github.com/ZenLiuCN/engine/modules/golang/reflect"
)

var (
	//go:embed encoding_gob.d.ts
	EncodingGobDefine   []byte
	EncodingGobDeclared = map[string]any{
		"newDecoder":   gob.NewDecoder,
		"newEncoder":   gob.NewEncoder,
		"register":     gob.Register,
		"registerName": gob.RegisterName,

		"emptyCommonType":    engine.Empty[gob.CommonType],
		"emptyRefCommonType": engine.EmptyRefer[gob.CommonType],
		"refOfCommonType":    engine.ReferOf[gob.CommonType],
		"unRefCommonType":    engine.UnRefer[gob.CommonType]}
)

func init() {
	engine.RegisterModule(EncodingGobModule{})
}

type EncodingGobModule struct{}

func (S EncodingGobModule) Identity() string {
	return "golang/encoding/gob"
}
func (S EncodingGobModule) TypeDefine() []byte {
	return EncodingGobDefine
}
func (S EncodingGobModule) Exports() map[string]any {
	return EncodingGobDeclared
}
