// Code generated by define_gene; DO NOT EDIT.
package larkpassport

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/context"
	_ "github.com/ZenLiuCN/engine/modules/github/com/larksuite/oapi-sdk-go/v3/core"
	"github.com/larksuite/oapi-sdk-go/v3/service/passport/v1"
)

var (
	//go:embed github_com_larksuite_oapi-sdk-go_v3_service_passport_v1.d.ts
	GithubComLarksuiteOapiSdkGo3ServicePassport1Define   []byte
	GithubComLarksuiteOapiSdkGo3ServicePassport1Declared = map[string]any{
		"UserIdTypeOpenId":                  larkpassport.UserIdTypeOpenId,
		"UserIdTypeUnionId":                 larkpassport.UserIdTypeUnionId,
		"newCredentialsBuilder":             larkpassport.NewCredentialsBuilder,
		"newDepartmentIdBuilder":            larkpassport.NewDepartmentIdBuilder,
		"newDeviceBuilder":                  larkpassport.NewDeviceBuilder,
		"newQuerySessionReqBodyBuilder":     larkpassport.NewQuerySessionReqBodyBuilder,
		"newQuerySessionReqBuilder":         larkpassport.NewQuerySessionReqBuilder,
		"New":                               larkpassport.New,
		"newIdpCredentialIdBuilder":         larkpassport.NewIdpCredentialIdBuilder,
		"newMaskSessionBuilder":             larkpassport.NewMaskSessionBuilder,
		"newQuerySessionPathReqBodyBuilder": larkpassport.NewQuerySessionPathReqBodyBuilder,
		"UserIdTypeUserId":                  larkpassport.UserIdTypeUserId,

		"emptyQuerySessionRespData":              engine.Empty[larkpassport.QuerySessionRespData],
		"emptyRefQuerySessionRespData":           engine.EmptyRefer[larkpassport.QuerySessionRespData],
		"refOfQuerySessionRespData":              engine.ReferOf[larkpassport.QuerySessionRespData],
		"unRefQuerySessionRespData":              engine.UnRefer[larkpassport.QuerySessionRespData],
		"emptyIdpCredentialId":                   engine.Empty[larkpassport.IdpCredentialId],
		"emptyRefIdpCredentialId":                engine.EmptyRefer[larkpassport.IdpCredentialId],
		"refOfIdpCredentialId":                   engine.ReferOf[larkpassport.IdpCredentialId],
		"unRefIdpCredentialId":                   engine.UnRefer[larkpassport.IdpCredentialId],
		"emptyQuerySessionReqBodyBuilder":        engine.Empty[larkpassport.QuerySessionReqBodyBuilder],
		"emptyRefQuerySessionReqBodyBuilder":     engine.EmptyRefer[larkpassport.QuerySessionReqBodyBuilder],
		"refOfQuerySessionReqBodyBuilder":        engine.ReferOf[larkpassport.QuerySessionReqBodyBuilder],
		"unRefQuerySessionReqBodyBuilder":        engine.UnRefer[larkpassport.QuerySessionReqBodyBuilder],
		"emptyIdpCredentialIdBuilder":            engine.Empty[larkpassport.IdpCredentialIdBuilder],
		"emptyRefIdpCredentialIdBuilder":         engine.EmptyRefer[larkpassport.IdpCredentialIdBuilder],
		"refOfIdpCredentialIdBuilder":            engine.ReferOf[larkpassport.IdpCredentialIdBuilder],
		"unRefIdpCredentialIdBuilder":            engine.UnRefer[larkpassport.IdpCredentialIdBuilder],
		"emptyV1":                                engine.Empty[larkpassport.V1],
		"emptyRefV1":                             engine.EmptyRefer[larkpassport.V1],
		"refOfV1":                                engine.ReferOf[larkpassport.V1],
		"unRefV1":                                engine.UnRefer[larkpassport.V1],
		"emptyCredentialsBuilder":                engine.Empty[larkpassport.CredentialsBuilder],
		"emptyRefCredentialsBuilder":             engine.EmptyRefer[larkpassport.CredentialsBuilder],
		"refOfCredentialsBuilder":                engine.ReferOf[larkpassport.CredentialsBuilder],
		"unRefCredentialsBuilder":                engine.UnRefer[larkpassport.CredentialsBuilder],
		"emptyDeviceBuilder":                     engine.Empty[larkpassport.DeviceBuilder],
		"emptyRefDeviceBuilder":                  engine.EmptyRefer[larkpassport.DeviceBuilder],
		"refOfDeviceBuilder":                     engine.ReferOf[larkpassport.DeviceBuilder],
		"unRefDeviceBuilder":                     engine.UnRefer[larkpassport.DeviceBuilder],
		"emptyQuerySessionPathReqBodyBuilder":    engine.Empty[larkpassport.QuerySessionPathReqBodyBuilder],
		"emptyRefQuerySessionPathReqBodyBuilder": engine.EmptyRefer[larkpassport.QuerySessionPathReqBodyBuilder],
		"refOfQuerySessionPathReqBodyBuilder":    engine.ReferOf[larkpassport.QuerySessionPathReqBodyBuilder],
		"unRefQuerySessionPathReqBodyBuilder":    engine.UnRefer[larkpassport.QuerySessionPathReqBodyBuilder],
		"emptyQuerySessionReq":                   engine.Empty[larkpassport.QuerySessionReq],
		"emptyRefQuerySessionReq":                engine.EmptyRefer[larkpassport.QuerySessionReq],
		"refOfQuerySessionReq":                   engine.ReferOf[larkpassport.QuerySessionReq],
		"unRefQuerySessionReq":                   engine.UnRefer[larkpassport.QuerySessionReq],
		"emptyQuerySessionReqBody":               engine.Empty[larkpassport.QuerySessionReqBody],
		"emptyRefQuerySessionReqBody":            engine.EmptyRefer[larkpassport.QuerySessionReqBody],
		"refOfQuerySessionReqBody":               engine.ReferOf[larkpassport.QuerySessionReqBody],
		"unRefQuerySessionReqBody":               engine.UnRefer[larkpassport.QuerySessionReqBody],
		"emptyQuerySessionResp":                  engine.Empty[larkpassport.QuerySessionResp],
		"emptyRefQuerySessionResp":               engine.EmptyRefer[larkpassport.QuerySessionResp],
		"refOfQuerySessionResp":                  engine.ReferOf[larkpassport.QuerySessionResp],
		"unRefQuerySessionResp":                  engine.UnRefer[larkpassport.QuerySessionResp],
		"emptyDevice":                            engine.Empty[larkpassport.Device],
		"emptyRefDevice":                         engine.EmptyRefer[larkpassport.Device],
		"refOfDevice":                            engine.ReferOf[larkpassport.Device],
		"unRefDevice":                            engine.UnRefer[larkpassport.Device],
		"emptyMaskSession":                       engine.Empty[larkpassport.MaskSession],
		"emptyRefMaskSession":                    engine.EmptyRefer[larkpassport.MaskSession],
		"refOfMaskSession":                       engine.ReferOf[larkpassport.MaskSession],
		"unRefMaskSession":                       engine.UnRefer[larkpassport.MaskSession],
		"emptyDepartmentIdBuilder":               engine.Empty[larkpassport.DepartmentIdBuilder],
		"emptyRefDepartmentIdBuilder":            engine.EmptyRefer[larkpassport.DepartmentIdBuilder],
		"refOfDepartmentIdBuilder":               engine.ReferOf[larkpassport.DepartmentIdBuilder],
		"unRefDepartmentIdBuilder":               engine.UnRefer[larkpassport.DepartmentIdBuilder],
		"emptyMaskSessionBuilder":                engine.Empty[larkpassport.MaskSessionBuilder],
		"emptyRefMaskSessionBuilder":             engine.EmptyRefer[larkpassport.MaskSessionBuilder],
		"refOfMaskSessionBuilder":                engine.ReferOf[larkpassport.MaskSessionBuilder],
		"unRefMaskSessionBuilder":                engine.UnRefer[larkpassport.MaskSessionBuilder],
		"emptyQuerySessionReqBuilder":            engine.Empty[larkpassport.QuerySessionReqBuilder],
		"emptyRefQuerySessionReqBuilder":         engine.EmptyRefer[larkpassport.QuerySessionReqBuilder],
		"refOfQuerySessionReqBuilder":            engine.ReferOf[larkpassport.QuerySessionReqBuilder],
		"unRefQuerySessionReqBuilder":            engine.UnRefer[larkpassport.QuerySessionReqBuilder],
		"emptyCredentials":                       engine.Empty[larkpassport.Credentials],
		"emptyRefCredentials":                    engine.EmptyRefer[larkpassport.Credentials],
		"refOfCredentials":                       engine.ReferOf[larkpassport.Credentials],
		"unRefCredentials":                       engine.UnRefer[larkpassport.Credentials],
		"emptyDepartmentId":                      engine.Empty[larkpassport.DepartmentId],
		"emptyRefDepartmentId":                   engine.EmptyRefer[larkpassport.DepartmentId],
		"refOfDepartmentId":                      engine.ReferOf[larkpassport.DepartmentId],
		"unRefDepartmentId":                      engine.UnRefer[larkpassport.DepartmentId]}
)

func init() {
	engine.RegisterModule(GithubComLarksuiteOapiSdkGo3ServicePassport1Module{})
}

type GithubComLarksuiteOapiSdkGo3ServicePassport1Module struct{}

func (S GithubComLarksuiteOapiSdkGo3ServicePassport1Module) Identity() string {
	return "github.com/larksuite/oapi-sdk-go/v3/service/passport/v1"
}
func (S GithubComLarksuiteOapiSdkGo3ServicePassport1Module) TypeDefine() []byte {
	return GithubComLarksuiteOapiSdkGo3ServicePassport1Define
}
func (S GithubComLarksuiteOapiSdkGo3ServicePassport1Module) Exports() map[string]any {
	return GithubComLarksuiteOapiSdkGo3ServicePassport1Declared
}
