// Code generated by define_gene; DO NOT EDIT.
package filepath

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/io/fs"
	"path/filepath"
)

var (
	//go:embed path_filepath.d.ts
	PathFilepathDefine   []byte
	PathFilepathDeclared = map[string]any{
		"abs":           filepath.Abs,
		"split":         filepath.Split,
		"volumeName":    filepath.VolumeName,
		"ErrBadPattern": filepath.ErrBadPattern,
		"isLocal":       filepath.IsLocal,
		"ListSeparator": filepath.ListSeparator,
		"rel":           filepath.Rel,
		"SkipAll":       filepath.SkipAll,
		"toSlash":       filepath.ToSlash,
		"glob":          filepath.Glob,
		"splitList":     filepath.SplitList,
		"base":          filepath.Base,
		"clean":         filepath.Clean,
		"hasPrefix":     filepath.HasPrefix,
		"dir":           filepath.Dir,
		"evalSymlinks":  filepath.EvalSymlinks,
		"ext":           filepath.Ext,
		"SkipDir":       filepath.SkipDir,
		"join":          filepath.Join,
		"match":         filepath.Match,
		"Separator":     filepath.Separator,
		"walk":          filepath.Walk,
		"walkDir":       filepath.WalkDir,
		"fromSlash":     filepath.FromSlash,
		"isAbs":         filepath.IsAbs,
	}
)

func init() {
	engine.RegisterModule(PathFilepathModule{})
}

type PathFilepathModule struct{}

func (S PathFilepathModule) Identity() string {
	return "golang/path/filepath"
}
func (S PathFilepathModule) TypeDefine() []byte {
	return PathFilepathDefine
}
func (S PathFilepathModule) Exports() map[string]any {
	return PathFilepathDeclared
}
