// Code generated by define_gene; DO NOT EDIT.
package tabwriter

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/modules/golang/io"
	"text/tabwriter"
)

var (
	//go:embed text_tabwriter.d.ts
	TextTabwriterDefine   []byte
	TextTabwriterDeclared = map[string]any{
		"TabIndent":           tabwriter.TabIndent,
		"AlignRight":          tabwriter.AlignRight,
		"Debug":               tabwriter.Debug,
		"DiscardEmptyColumns": tabwriter.DiscardEmptyColumns,
		"Escape":              tabwriter.Escape,
		"FilterHTML":          tabwriter.FilterHTML,
		"newWriter":           tabwriter.NewWriter,
		"StripEscape":         tabwriter.StripEscape,
	}
)

func init() {
	engine.RegisterModule(TextTabwriterModule{})
}

type TextTabwriterModule struct{}

func (S TextTabwriterModule) Identity() string {
	return "golang/text/tabwriter"
}
func (S TextTabwriterModule) TypeDefine() []byte {
	return TextTabwriterDefine
}
func (S TextTabwriterModule) Exports() map[string]any {
	return TextTabwriterDeclared
}
