// Code generated by define_gene; DO NOT EDIT.
package fnv

import (
	_ "embed"
	"github.com/ZenLiuCN/engine"

	_ "github.com/ZenLiuCN/engine/golang/hash"
	"hash/fnv"
)

var (
	//go:embed hash_fnv.d.ts
	HashFnvDefine   []byte
	HashFnvDeclared = map[string]any{
		"new128a": fnv.New128a,
		"new32":   fnv.New32,
		"new32a":  fnv.New32a,
		"new64":   fnv.New64,
		"new64a":  fnv.New64a,
		"new128":  fnv.New128,
	}
)

func init() {
	engine.RegisterModule(HashFnvModule{})
}

type HashFnvModule struct{}

func (S HashFnvModule) Identity() string {
	return "golang/hash/fnv"
}
func (S HashFnvModule) TypeDefine() []byte {
	return HashFnvDefine
}
func (S HashFnvModule) Exports() map[string]any {
	return HashFnvDeclared
}
